container:
  image: node:9.4.0
  cpu: 1.5
  memory: 2Gb

build_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  relay_script: yarn run relay
  build_script: yarn run build
