container:
  image: node:9.6.1

build_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  relay_script: yarn run relay
  build_script: yarn run build
